# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MathEvaluate/math.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17MathEvaluate/math.proto\x12\x04math\" \n\nstrRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\" \n\x0e\x64oubleResponse\x12\x0e\n\x06number\x18\x01 \x01(\x01\x32?\n\tevaluator\x12\x32\n\x08\x65valuate\x12\x10.math.strRequest\x1a\x14.math.doubleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MathEvaluate.math_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STRREQUEST']._serialized_start=33
  _globals['_STRREQUEST']._serialized_end=65
  _globals['_DOUBLERESPONSE']._serialized_start=67
  _globals['_DOUBLERESPONSE']._serialized_end=99
  _globals['_EVALUATOR']._serialized_start=101
  _globals['_EVALUATOR']._serialized_end=164
# @@protoc_insertion_point(module_scope)
