# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import math_pb2 as MathEvaluate_dot_math__pb2


class evaluatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.evaluate = channel.unary_unary(
                '/math.evaluator/evaluate',
                request_serializer=MathEvaluate_dot_math__pb2.strRequest.SerializeToString,
                response_deserializer=MathEvaluate_dot_math__pb2.doubleResponse.FromString,
                )


class evaluatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_evaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.evaluate,
                    request_deserializer=MathEvaluate_dot_math__pb2.strRequest.FromString,
                    response_serializer=MathEvaluate_dot_math__pb2.doubleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'math.evaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class evaluator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/math.evaluator/evaluate',
            MathEvaluate_dot_math__pb2.strRequest.SerializeToString,
            MathEvaluate_dot_math__pb2.doubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
